poll: Check if _REDIR_TIME64 is defined
Treat _REDIR_TIME64 being undefined like being set to 0.

This fixes the following compile error in strace:
```
In file included from pathtrace.c:12:
/include/fortify/poll.h:46:30: error: "_REDIR_TIME64" is not defined, evaluates to 0 [-Werror=undef]
   46 | #if defined(_GNU_SOURCE) && !_REDIR_TIME64
      |                              ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>