Check if FORTIFY_USE_NATIVE_CHK is defined
The previews code tried to get the value defined for
FORTIFY_USE_NATIVE_CHK and this resulted in some build errors like
this:
```
/include/fortify/stdio.h: In function 'vsnprintf':
/include/fortify/stdio.h:155:49: error: "FORTIFY_USE_NATIVE_CHK" is not defined, evaluates to 0 [-Werror=undef]
  155 | #if __has_builtin(__builtin___vsnprintf_chk) && FORTIFY_USE_NATIVE_CHK
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~
```

Check if it is defined instead.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>